<?php

declare(strict_types=1);
/**
 * This file is part of MineAdmin.
 *
 * @link     https://www.mineadmin.com
 * @document https://doc.mineadmin.com
 * @contact  root@imoi.cn
 * @license  https://github.com/mineadmin/MineAdmin/blob/master/LICENSE
 */

namespace Mine\Admin\Tests\Bundle\Controller;

use Hyperf\Config\Config;
use Hyperf\Context\ApplicationContext;
use Hyperf\Contract\ConfigInterface;
use Mine\Admin\Bundle\Request\PassportRequest;
use Mine\SecurityBundle\Security;
use Mockery as m;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 * @coversNothing
 */
class PassportController extends TestCase
{
    protected function setUp(): void
    {
        $container = ApplicationContext::getContainer();
        $config = new Config(['admin' => include dirname(__DIR__, 3) . '/publish/admin.php']);
        $container->set(ConfigInterface::class, $config);
        $container->define(\Mine\SecurityBundle\Config::class, \Mine\Admin\Security\Config::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLogin(): void
    {
        $reflection = new \ReflectionClass(\Mine\Admin\Bundle\Controller\PassportController::class);
        $method = $reflection->getMethod('login');
        $request = m::mock(PassportRequest::class);
        $request->allows('validated')->andReturn([
            'username' => 'admin',
            'password' => '123456',
        ]);
        $security = ApplicationContext::getContainer()->get(Security::class);
        $method->invoke(m::mock(\Mine\Admin\Bundle\Controller\PassportController::class), $security, $request);
    }
}
