<?php

declare(strict_types=1);
/**
 * This file is part of MineAdmin.
 *
 * @link     https://www.mineadmin.com
 * @document https://doc.mineadmin.com
 * @contact  root@imoi.cn
 * @license  https://github.com/mineadmin/MineAdmin/blob/master/LICENSE
 */

namespace Mine\Admin\Bundle\Tests\Cases\Dto;

use Mine\Admin\Bundle\Dto\UserLoginDto;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 * @coversNothing
 */
class UserLoginDtoTest extends TestCase
{
    protected UserLoginDto $dto;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dto = new UserLoginDto('mine', '123456');
    }

    public function testSetPassword(): void
    {
        $this->dto->setPassword('1111');
        $this->assertSame($this->dto->getPassword(), '1111');
        $this->assertSame($this->dto->password, '1111');
    }

    public function testSetUsername(): void
    {
        $this->dto->setUsername('xxx');
        $this->assertSame($this->dto->getUsername(), 'xxx');
        $this->assertSame($this->dto->username, 'xxx');
    }
}
